name: Test Migrations

on:
  pull_request:
    branches:
      - main # Trigger workflow on pull requests targeting the main branch

jobs:
  test-migrations:
    runs-on: ubuntu-latest
    environment: test

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OPENAI_SECRET: ${{ secrets.OPENAI_SECRET }}
      SUPABASE_URL: ${{ env.SUPABASE_URL }}
      SUPABASE_KEY: ${{ env.SUPABASE_KEY }}

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Set up PostgreSQL
        uses: Harmon758/postgresql-action@v2
        with:
          postgresql version: "17"
          database: local_db
          username: postgres
          password: postgres

      - name: Dump production database
        run: |
          pg_dump $DATABASE_URL > prod_dump.sql

      - name: Import into local database
        env:
          LOCAL_DATABASE_URL: postgres://postgres:postgres@localhost:5432/local_db
        run: |
          psql $LOCAL_DATABASE_URL < prod_dump.sql

      - name: Run migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/local_db
        run: yarn migrate:push
