name: Test Migrations

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

jobs:
  create_neon_branch:
    name: Create Neon Branch
    outputs:
      db_url: ${{ steps.create_neon_branch_encode.outputs.db_url }}
      db_url_with_pooler: ${{ steps.create_neon_branch_encode.outputs.db_url_with_pooler }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Neon Branch
        id: create_neon_branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          database: ${{ vars.DATABASE_ID }}
          branch_name: pr-${{ github.event.number }}/${{ inputs.branch_name }}/${{ github.sha }}
          username: ${{ vars.DATABASE_USERNAME }}
          api_key: ${{ secrets.NEON_API_KEY }}

  run_migrations:
    name: Run Migrations
    runs-on: ubuntu-latest
    environment: test

    env:
      DATABASE_URL: ${{ needs.create_neon_branch.outputs.db_url_with_pooler }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OPENAI_SECRET: ${{ secrets.OPENAI_SECRET }}
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    needs: create_neon_branch

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn

      - name: Run Migrations
        run: yarn migrate:push

  delete_neon_branch:
    name: Delete Neon Branch
    needs: [create_neon_branch, run_migrations]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: pr-${{ github.event.number }}/${{ inputs.branch_name }}/${{ github.sha }}
          api_key: ${{ secrets.NEON_API_KEY }}
