name: Pull Request Checks

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: Lint Debug Variant
    uses: ./.github/workflows/lint_action.yml

  format:
    name: Format Debug Variant
    uses: ./.github/workflows/format_action.yml

  test:
    name: Test Debug Variant
    uses: ./.github/workflows/test_action.yml

  migrate:
    name: Migrate Debug Variant
    runs-on: ubuntu-latest
    needs: [lint, format, test] # Ensure previous jobs are successful before running this job
    if: success()

    environment: test

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OPENAI_SECRET: ${{ secrets.OPENAI_SECRET }}
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

      - name: Print branch name
        run: |
          echo "Branch name: ${{ steps.branch_name.outputs.current_branch }}"

      - name: Create Neon Branch
        id: create_neon_branch
        uses: neondatabase/create-branch-action@v5
        with:
          api_key: ${{ secrets.NEON_API_KEY }}
          project_id: ${{ vars.NEON_PROJECT_ID }}
          database: ${{ vars.DATABASE_ID }}
          branch_name: pr/${{ steps.branch_name.outputs.current_branch }}-${{ github.event.pull_request.number }}
          username: ${{ vars.DATABASE_USER }}

      - uses: actions/checkout@v4
        if: success()

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        if: success()

        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn
        if: success()

      - name: Run Migration
        id: run_migration
        run: yarn migrate:push
        if: success()

      - name: Delete Neon Branch
        id: delete_neon_branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: pr/${{ steps.branch_name.outputs.current_branch }}-${{ github.event.pull_request.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
        if: ${{ success() && steps.create_neon_branch.outcome == 'success' && steps.run_migration.outcome == 'success' }}
