name: Pull Request Checks

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint Debug Variant
    uses: ./.github/workflows/lint_action.yml

  format:
    name: Format Debug Variant
    uses: ./.github/workflows/format_action.yml

  test:
    name: Test Debug Variant
    uses: ./.github/workflows/test_action.yml

  migrate:
    name: Migrate Debug Variant
    uses: ./.github/workflows/migrate_action.yml
    needs: [lint, format, test] # Make sure migrate waits for the previous jobs
    if: success() # This ensures migrate only runs if all previous jobs succeed
