name: Migrate CI

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint Debug Variant
    uses: ./.github/workflows/lint_action.yml

  format:
    name: Format Debug Variant
    uses: ./.github/workflows/format_action.yml

  test:
    name: Test Debug Variant
    uses: ./.github/workflows/test_action.yml
