name: Pull Request Checks

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    name: Setup
    outputs:
      branch_name: ${{ steps.branch_name.outputs.current_branch }}
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

      - name: Print branch name
        run: |
          echo "Branch name: ${{ steps.branch_name.outputs.current_branch }}"

  lint:
    name: Lint Debug Variant
    uses: ./.github/workflows/lint_action.yml

  format:
    name: Format Debug Variant
    uses: ./.github/workflows/format_action.yml

  test:
    name: Test Debug Variant
    uses: ./.github/workflows/test_action.yml

  migrate:
    name: Migrate Debug Variant
    uses: ./.github/workflows/migrate_action.yml
    needs: [setup, lint, format, test] # Make sure migrate waits for the previous jobs
    if: success() # This ensures migrate only runs if all previous jobs succeed
    with:
      branch_name: ${{ needs.setup.outputs.branch_name }} # Pass branch name from setup job
