name: Sync Staging with Main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "slyduda" 
          git config --global user.email "me@slyduda.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check out staging branch
        run: git checkout staging

      - name: Merge main into staging with conflict resolution
        run: |
          git merge origin/main --no-ff --allow-unrelated-histories || true
          git checkout --theirs .
          git add .
          git commit -m "Force merge: Sync staging with main"

      - name: Force push changes to staging
        run: |
          git push origin staging --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
